name: PR Checker
on:
    pull_request:
        branches:
            - "dev"
    workflow_dispatch:
jobs:
    typescript:
        name: 🔨 TypeScript Checker
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: ⤵️ Checkout "dev"
              uses: actions/checkout@v4
            - name: 🛠️ Setup Bun
              uses: oven-sh/setup-bun@v2
            - name: 🛠️ Install Dependencies
              run: |
                  bun install
            - name: ⏳ Checking TypeScript...
              run: |
                  bun run ts
